### ISSUE TITLE
How to dynamically build a filter expressions with reduce(_ and_)

### ISSUE THREAD

**Issue by tolomaus** [scanamo/scanamo#1183]
I'm struggling to dynamically create a dynamic filter expression that combines multiple expressions using an AndCondition:
```scala
    val filter =
      Array(
        AttributeName.of("listA") contains itemA,
        AttributeName.of("listB") contains itemB
      )
        .reduce(_ and _)
```

It fails with

```
type mismatch;
 found   : org.scanamo.query.AndCondition[org.scanamo.query.Contains,org.scanamo.query.Contains]
 required: org.scanamo.query.Contains
        .reduce(_ and _)
```

The `reduce()` requires a common type between AndCondition[Contains,Contains] and Contains, any idea how I can make this work?

I'm already using the same approach for update expressons and there it works fine because the AndUpdate extends the UpdateExpression

**Comment by regiskuckaertz** [comment]
@tolomaus sorry about that, the two algebras were designed at different times I think. It should be easy but actually is not, first off the type of `Array.reduce` forces the result type to be a super-type of the element type, which is why it works for updates. Second, `AndCondition` takes two type parameters. So
```scala
filter(0) and filter(1):
  AndCondition[Contains, Contains]
```
but
```scala
filter(0) and filter(1) and filter(2):
  AndCondition[AndCondition[Contains, Contains], Contains]
```
so, to write a reduce that works for this, you will need to go beyond simple arrays and functions, something like (not tested):
```scala
trait ConditionReduce[Xs <: HList] {
  type Z
  def reduceAnd(xs: Xs): Z
}
object ConditionReduce {
  implicit val hNilReduce: ConditionReduce[HNil] = new ConditionReduce[HNil] {
    type Z = True.type
    def reduceAnd(xs: HNil): Z = True // we don't have `True` but it could be written
  }
  implicit def hConsReduce[X, Xs](implicit X: ConditionExpression[X], Xs: ConditionReduce[Xs]): ConditionReduce[X ::: Xs] =
    new ConditionReduce[X ::: Xs] {
      type Z = AndCondition[X, Xs.Z]
      def reduceAnd(xs: X ::: Xs): Z = xs.head and Xs.reduceAnd(xs.tail)
    }
}
```
This is ugly as hell but given how all the conditions are defined, it is the only way currently. Ha, you will also need a proof that `Z` has a `ConditionExpression` so the above is probably not enough. So as you can see, the library needs a bit of a makeover there 😄

**Comment by tolomaus** [comment]
Thanks for your take on this @regiskuckaertz ! I'm not too familiar with the advanced scala features like cats, shapeless etc so I'm afraid I have reached my limits here ;-)

Ideally scanamo would support all possible dynamodb features (like the reduce), but in reality this will not always be possible. In these cases my current workaround is to manipulate the underlying QueryRequest directly.
