### ISSUE TITLE
Enum value types mapped incorrectly when used directly in queries

### ISSUE THREAD

**Issue by ivashin** [scanamo/scanamo#138]
When an enumeration is defined as sealed trait + case objects hierarchy, using enum values directly in update operations results in record being corrupted because of incorrect mapping. Sample below fails with `PropertyReadError(status,TypeCoercionError(java.lang.Exception: {M: {},} is not a recognised member of the Enumeration))` error.

```scala
object EnumTest {
  sealed trait Status
  case object Pending extends Status
  case object Completed extends Status

  case class Record(id: String, status: Status)
}

class EnumTest extends FunSpec with Matchers {
  import EnumTest._

  lazy val client = AmazonDynamoDBClientBuilder.standard().withEndpointConfiguration(new EndpointConfiguration("http://localhost:8000", "")).build()
  lazy val table = Table[Record]("TestTable")

  describe("Scanamo") {
    val id = "ABC"
    val putRequest = table.put(Record(id, Pending))
    Scanamo.exec(client)(putRequest)

    it("should update enum value") {
      val updateRequest = table.update('id -> id, set('status -> Completed))
      val updated = Scanamo.exec(client)(updateRequest)
      updated.right.value should equal(Record(id, Completed))
    }
  }
}
```

Similarly, enum values can't be used directly in conditional clauses.

When enum is casted to base trait, either by `.asInstanceOf[Status]` or `val status: Status = `, everything works as expected.

**Comment by philwills** [comment]
#140 should stop it accidentally compiling. Rather than using an `asInstanceOf`, you could write

```scala
val updateRequest = table.update('id -> id, set[Status]('status -> Completed))
```
which is a bit less ugly. 

Still not ideal, but I'm unsure how to improve this with this encoding of an enumeration without changing the variance of `DynamoFormat`, which is a bit too scary for my liking.

Down the line it would be good to do something like https://github.com/kailuowang/henkan does with it's `set` method to exploit the fact that the `Table` knows the types of its fields, but that feels a pretty chunky change.
