### ISSUE TITLE
where is LocalDynamoDB?

### ISSUE THREAD

**Issue by poohsen** [scanamo/scanamo#189]
The basic usage example mentions LocalDynamoDB but I don't see it in the master branch nor in the 1.0.0-M2, M3 or M4 builds. Where does this object come from? Feels like I'm missing something major... a little help would be much appreciated

**Comment by mattbernst** [comment]
The examples are broken because LocalDynamoDB isn't accessible that way any more. If you want to look at it, see: https://github.com/scanamo/scanamo/blob/master/scanamo/src/test/scala/com/gu/scanamo/LocalDynamoDB.scala

If you just want to run the examples against a local dynamo db instance, you can do something like

```
val client = {
    val conf = new EndpointConfiguration("http://localhost:8000", "us-east-1")
    AmazonDynamoDBClientBuilder.standard().withEndpointConfiguration(conf).build()
  }
```

wherever the examples currently show `val client = LocalDynamoDB.client()`.

**Comment by poohsen** [comment]
that worked. thanks!
