### ISSUE TITLE
Remove `DynamoResultStream`

### ISSUE THREAD

**Issue by regiskuckaertz** [scanamo/scanamo#275]
Scanamo has logic so that the 1MB limit for the result set size is circumvented, but this applies to all queries/scans regardless of users' intent. It may be problematic in some situations (as in #181 ) and prevents running some computations in constant space.

I propose to get rid of it, or at the very least to make this an opt-in feature, i.e. by default the behaviour of Scanamo strictly follows that of DynamoDB.

What do you think @philwills ?

**Comment by philwills** [comment]
One of my original design goals was to explicitly move away from the Dynamo API and make simple things simple at the expense of not supporting some more complex scenarios because when I was learning Dynamo, I made mistakes with the API *all* the time. I'd love to have a clean way of streaming results, but not at the expense of exposing the Dynamo API. 

However, that's just like, my opinion, man. There's definitely value in both design directions.

**Comment by regiskuckaertz** [comment]
I think this is well put and I'll add it [to the doc](#272 ), we must keep that as a design goal. I feel if we correctly separate the concerns of building up a request, running a query and taking down a result in separate components, it will give us the ability to create more user-friendly APIs that just combine these things together and offer an advanced API to people who need to get closer to the metal.

A picture is taking shape in my mind where `ScanamoOps ~ W[I] => M[O]`:
```scala
Put ~ W[PutItemRequest] => M[PutItemResult]
Get ~ W[GetItemRequest] => M[GetItemResult]
etc.
```
I'm not yet sure where this is going, but on top of that, it seems we could build a whole vocabulary of useful combinators of the form:
```scala
def op[I0, O0](...): ScanamoOps[W, M, I0, O0]
```
and reach that goal:
```scala
val request = put(item)
  .ifNotExists(key)    // conditional put
  .consuming(capacity) // return consumed capacity
  .collect(metrics)   // return collection metrics
```
this all through `contramap`ping the input or `map`ping the output.
